envSecrets:
  client-id:     <sealedsecret of OAUTH2_PROXY_CLIENT_ID>
  client-secret: <sealedsecret of OAUTH2_PROXY_CLIENT_SECRET>
  cookie-secret: <sealedsecret of OAUTH2_PROXY_COOKIE_SECRET>

# sealedsecrets have to be generated per environment
namespace: kube-system

# also, for the 3 strings above, you need to start from a
# Secret resource (local file if you want, as by example:
#  https://github.com/bitnami-labs/sealed-secrets#usage ) 
# and put em in place, in this values.yaml file 
# 
# generating each encryption in a separated manner would lead to
# SealedSecret not being able to decrypt and generate the final Secret
#
# so, start from the Sealed resource in the oauth2-proxy template

oauth2-proxy:
  # cherry-pick what you need from oauth2-proxy/values.yaml file
  config:
    existingSecret: helm-sso
  