apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $secret := $.Values.envSecrets }}
    {{ $key }}: {{ $secret | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      namespace: {{ .Values.namespace }}
